services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./server/app:/code/app
    links:
      - db-postgres:db-postgres

  db-postgres:
    image: kartoza/postgis:18-3.6
    ports:
        - "5433:5432"
    env_file: .env
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASSWORD}
        - ALLOW_IP_RANGE=0.0.0.0/0
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
        - FORCE_SSL=FALSE
    volumes:
      - ./data/db:/data
    restart: on-failure
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m

  python-env:
    image: vikineema/deafrica-water-quality:sha-c60eb53
    environment:
      - WATERBODIES_DB_NAME=${POSTGRES_DB}
      - WATERBODIES_DB_USER=${POSTGRES_USER}
      - WATERBODIES_DB_PASS=${POSTGRES_PASSWORD}
      - WATERBODIES_DB_HOST=db-postgres
      - WATERBODIES_DB_PORT=5432
    volumes:
      - ./sample_waterbodies.db:/tmp/sample_waterbodies.db
      - ./scripts:/home/jovyan/scripts
    depends_on:
        db-postgres:
          condition: service_healthy
    entrypoint: ["tail", "-f", "/dev/null"]
